### ISSUE TITLE
This is not an open source project if the API code is not available

### ISSUE THREAD

**Issue by graypegg** [psolbach/iconbin#19]
Just noticed the API code is missing, would be good to have the API on github.

**Comment by psolbach** [comment]
Will look into it, but it's dirt simple. Basically just a beefed up `hasOwnProperty` if clause and some caching.

**Comment by graypegg** [comment]
Just for the sake of your app being truly open source is all, plus, you never know what people can add.

**Comment by psolbach** [comment]
Boom. Done.
