### ISSUE TITLE
No CORS mode or JSONP support

### ISSUE THREAD

**Issue by graypegg** [psolbach/iconbin#21]
The JSON API should support Cross-Origin Requests because the API is potentially useful in the browser. JSONP support would also work.
### Recreating the issue:

Try running the following in your browser's JS Console on a site other than https://iconbin.com/

``` javascript
fetch("https://iconbin.com/api/instagram.com")
    .then(function(res){
        return res.json();
    })
    .then(function(data){
        // `data` will never be resolved due to
        // the Cross-Origin Request policy.
        console.log(data);
    })
```
### Solution

Add the [CORS headers](http://enable-cors.org/server_expressjs.html) to the routes in the Express app. Then requests can be made like this

``` javascript
fetch("https://iconbin.com/api/instagram.com", { mode: "cors" })
    .then(function(res){
        return res.json();
    })
    .then(function(data){
        // `data` is resolved!
        console.log(data);
    })
```

**Comment by psolbach** [comment]
Good point. As I've added the API code now you're very welcome to fix this yourself if you like.
