### ISSUE TITLE
API call on website does not work

### ISSUE THREAD

**Issue by graypegg** [psolbach/iconbin#22]
The example API call on the website is:

``` javascript
request({
   url: "https://iconbin.com/api/instagram.com,
   json: true
}, cb)
```

It doesn't explain the purpose very well (cb isn't synonymous with call back functions)~~, and doesn't offer any useable code.~~ (nvm, realized this is the [Request API](https://github.com/request/request) could be better explained though, possible as an option in a language selector like checkbox 3?)
- [x] Needs closing quote on URL.
- [ ] Should be rewritten using [the Fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API)~~, jQuery's AJAX function or both, instead of pseudo-code.~~
- [ ] Show other examples in other languages, maybe something similar to how Postmark does it? (see below)

![Postmark API Example](https://cloud.githubusercontent.com/assets/8439945/15916789/2d048434-2dc4-11e6-91d9-2bcdee224a40.jpg)

**Comment by psolbach** [comment]
I agree about 1. Reasoning about 2, 3: The example call is sufficiently abstract as to allow developers to get the point, sort of like pseudo-code would. We're only dealing with a simple request here, so I think language tabs are overkill. Also, since the fetch API isn't available yet in Node we need to enable CORS first #21 for that to make sense.

**Comment by tschoffelen** [comment]
Agreed, the current example makes it sufficiently clear how to use the API, so no need to execute points 2 or 3 I think.

**Comment by psolbach** [comment]
@toish I added a rudimentary webserver just for the API as per your request. Cross-domain fetch() is now implemented by @tschoffelen. While icons are continuously delivered to server, these changes will be reflected later during the day.
